version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Install dependencies...
  pre_build:
    commands:
      - echo Pre-build phase...
      - chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading the build artifacts...

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
  bucket-name: 'ifn-longvacation-bucket' # 내가 생성한 bucket 이름
  path: 'build-artifacts'