springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  openapi:
    info:
      title: Sample API
      description: API documentation for the Sample project
      version: v0.0.1
      contact:
        name: Support Team
        email: support@longvacation.com

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
